default_language_version:
  python: python3

repos:
- repo: local
  hooks:
  - id: ruff
    name: ruff
    alias: ruff
    types: [python]
    entry: uv run ruff check --fix
    language: system
  - id: ruff-format
    name: ruff-format
    alias: ruff-format
    types: [python]
    entry: uv run ruff format
    language: system
  - id: uv-lock-check
    name: uv-lock-check
    alias: uv-lock-check
    entry: uv lock --check
    language: system
    pass_filenames: false
    always_run: true
  - id: pytest
    name: pytest
    alias: pytest
    types: [python]
    entry: uv run pytest -v tests/ -s
    language: system
    always_run: true
    pass_filenames: false
